- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Install RKE2 Server
      dnf:
        name: rke2-server
        state: latest
    - name: Enable RKE2 Server
      systemd:
        state: started
        name: rke2-server
        enabled: true